localable:
  queryParameters:
    locale:
      description: Локаль для переводов
      enum: [en, ru]
      example: ru
      default: ru


pageable:
  queryParameters:
    limit:
      description: Кол-во записей в списке
      type: number
      required: false
      minimum: 1
      maximum: 30
    offset:
      description: Отступ для записей
      type: number
      minimum: 0
      required: false

hasCommonErrors:
  responses:
    404:
      body:
        application/json:
          type: VndCustomErrorJson

hasHeaderMissing:
  responses:
    403:
      body:
        application/json:
          type: VndCustomErrorJson

hasErrors:
  responses:
    400:
      body:
        application/json:
          type: VndCustomErrorJson
      description: |
        Описание кодов ошибок <br>

    422:
      body:
        application/json:
          type: VndCustomErrorJson
      description: |
        Описание кодов ошибок <br>

    500:
      body:
        application/json:
          type: VndCustomErrorJson
