#%RAML 1.0

title: Agency
version: 0.1
mediaType: application/json
urlPrefix: /api

uses:
  types: types.raml
  caseTypes: cases/types.raml
  serviceTypes: services/types.raml
  partnerTypes: partners/types.raml
  settingsTypes: settings/types.raml
  branchTypes: branches/types.raml

traits: !include common.raml

/cases: !include cases/cases.raml
/services: !include services/services.raml
/partners: !include partners/partners.raml
/settings: !include settings/settings.raml
/branches: !include branches/branches.raml
