#%RAML 1.0

title: Agency
version: 0.1
mediaType: application/json
urlPrefix: /api

uses:
  types: types.raml

traits: !include common.raml

/cases:
  get:
    is: [hasErrors, hasCommonErrors, localable, pageable]
    description: "Список кейсов"
    responses:
      200:
        body:
          application/json:
            type: types.CaseListResponse
            example: !include cases/examples/ListResponse.json

  post:
    is: [hasHeaderMissing, hasCommonErrors, hasErrors]
    description: "Список кейсов, фильтрация"
    body:
      application/json:
        type: types.CaseFilterRequest
        example: !include cases/examples/PostListRequestExample.json
    responses:
      200:
        body:
          application/json:
            type: types.CaseListResponse
            example: !include cases/examples/ListResponse.json

  /{slug}:
    get:
      is: [hasErrors, hasCommonErrors, localable]
      description: "Детальный кейс"
      responses:
        200:
          body:
            application/json:
              type: types.CaseResponse
              example: !include cases/examples/ItemResponse.json

/branches:
  get:
    is: [hasErrors, hasCommonErrors, localable, pageable]
    description: "Список отраслей"
    responses:
      200:
        body:
          application/json:
            type: types.BranchListResponse
            example: !include branches/examples/BranchesListResponse.json

/services:
  get:
    is: [hasErrors, hasCommonErrors, localable, pageable]
    description: "Список услуг"
    responses:
      200:
        body:
          application/json:
            type: types.ServicesListResponse
            example: !include examples/ListServicesResponse.json
  /{slug}:
    get:
      is: [hasErrors, hasCommonErrors, localable]
      description: "Детальная страница услуги"
      responses:
        200:
          body:
            application/json:
              type: types.ServiceResponse
              example: !include examples/ServiceResponse.json

/pages:
  get:
    is: [hasErrors, hasCommonErrors, localable, pageable]
    description: "Список статичных страниц"
    responses:
      200:
        body:
          application/json:
            type: types.PagesListResponse
            example: !include examples/PagesListResponse.json

  /{slug}:
    get:
      is: [hasErrors, hasCommonErrors, localable]
      description: "Статичная страница"
      responses:
        200:
          body:
            application/json:
              type: types.PageResponse
              example: !include examples/PageResponse.json

/settings:
  get:
    is: [hasErrors, hasCommonErrors, localable]
    description: "Список настроек"
    responses:
      200:
        body:
          application/json:
            type: types.AllSettingsResponse
            example: !include examples/AllSettingsResponse.json

  /translations:
    get:
      is: [hasErrors, hasCommonErrors, localable]
      description: "Список переводов по локали"
      responses:
        200:
          body:
            application/json:
              type: types.TranslationListResponse
              example: !include examples/TranslationsListResponse.json

/partners:
  get:
    is: [hasErrors, hasCommonErrors, localable, pageable]
    description: "Список активных партнеров"
    responses:
      200:
        body:
          application/json:
            type: types.PartnersListResponse
