#%RAML 1.0 Library

types:
  Picture:
    properties:
      id:
        type: integer
      src:
        type: string
      filename:
        type: string
      description:
        type: string | nil
        required: false
      height:
        type: integer | nil
        required: false
      width:
        type: integer | nil
        required: false
      context:
        type: string | nil
        required: false
      copyright:
        type: string | nil
        required: false
      size:
        type: string

  VndCustomErrorJson:
    properties:
      code:
        type: string
      message:
        type: string
    additionalProperties: false
