services:
  app.admin.case:
    class: App\Admin\CaseAdmin
    arguments: [~, App\Entity\Cases, SonataAdminBundle:CRUD]
    tags:
      - { name: sonata.admin, manager_type: orm, audit: false, group: Кейсы, label: Список кейсов }

  app.admin.case_block:
    class: App\Admin\CaseBlockAdmin
    arguments: [ ~, App\Entity\CaseBlock, SonataAdminBundle:CRUD ]
    tags:
      - { name: sonata.admin, manager_type: orm, audit: false, group: Кейсы, label: Блоки кейса, show_in_dashboard: false }

  app.admin.branch:
    class: App\Admin\BranchAdmin
    arguments: [~, App\Entity\Branch, SonataAdminBundle:CRUD]
    tags:
      - { name: sonata.admin, manager_type: orm, audit: false, group: Кейсы, label: Список отраслей }

  app.admin.service:
    class: App\Admin\ServiceAdmin
    arguments: [ ~, App\Entity\Service, SonataAdminBundle:CRUD ]
    tags:
      - { name: sonata.admin, manager_type: orm, audit: false, group: Кейсы, label: Список услуг }

  app.admin.client:
    class: App\Admin\ClientAdmin
    arguments: [ ~, App\Entity\Client, SonataAdminBundle:CRUD ]
    tags:
      - { name: sonata.admin, manager_type: orm, audit: false, group: Кейсы, label: Клиенты, show_in_dashboard: false }

  app.admin.partner:
    class: App\Admin\PartnerAdmin
    arguments: [ ~, App\Entity\Partner, SonataAdminBundle:CRUD ]
    tags:
      - { name: sonata.admin, manager_type: orm, audit: false, group: Основной контент, label: Список партнеров }

  app.admin.settings:
    class: App\Admin\SettingsAdmin
    arguments: [ ~, App\Entity\Settings, SonataAdminBundle:CRUD ]
    tags:
      - { name: sonata.admin, manager_type: orm, audit: false, group: Основной контент, label: Общие настройки }

  app.admin.video:
    class: App\Admin\VideoAdmin
    arguments: [ ~, App\Entity\Video, SonataAdminBundle:CRUD ]
    tags:
      - { name: sonata.admin, manager_type: orm, audit: false, group: Основной контент, label: Видео ролики }

  app.admin.specialist:
    class: App\Admin\SpecialistAdmin
    arguments: [ ~, App\Entity\Specialist, SonataAdminBundle:CRUD ]
    tags:
      - { name: sonata.admin, manager_type: orm, audit: false, group: Основной контент, label: Специалисты }

  app.admin.media:
    class: App\Admin\MediaAdmin
    arguments: [ ~, App\Entity\Media, SonataAdminBundle:CRUD ]
    tags:
      - { name: sonata.admin, manager_type: orm, audit: false, group: Основной контент, label: Медиа-файл }

  app.admin.page:
    class: App\Admin\PageAdmin
    arguments: [ ~, App\Entity\Page, SonataAdminBundle:CRUD ]
    tags:
      - { name: sonata.admin, manager_type: orm, audit: false, group: Статичные страницы, label: Страницы }

  app.admin.page_treatment:
    class: App\Admin\PageTreatmentAdmin
    arguments: [ ~, App\Entity\PageTreatments, SonataAdminBundle:CRUD ]
    tags:
      - { name: sonata.admin, manager_type: orm, audit: false, group: Статичные страницы, label: Достижения, show_in_dashboard: false }
