parameters:
  jms_serializer.camel_case_naming_strategy.class: JMS\Serializer\Naming\IdenticalPropertyNamingStrategy
jms_serializer:
  handlers:
    datetime:
      default_format: "Y-m-d\\TH:i:s"
  visitors:
    xml_serialization:
      format_output: '%kernel.debug%'
    json_serialization:
      options:
        - JSON_UNESCAPED_SLASHES
        - JSON_PRESERVE_ZERO_FRACTION

  default_context:
    serialization:
      serialize_null: true
    deserialization:
      serialize_null: true
  property_naming:
    id: 'jms_serializer.identical_property_naming_strategy'
    separator: ''
    lower_case: false
    