sonata_media:
  # if you don't use default namespace configuration
  #class:
  #    media: MyVendor\MediaBundle\Entity\Media
  #    gallery: MyVendor\MediaBundle\Entity\Gallery
  #    gallery_has_media: MyVendor\MediaBundle\Entity\GalleryHasMedia
  db_driver: doctrine_orm # or doctrine_mongodb, doctrine_phpcr it is mandatory to choose one here
  default_context: default # you need to set a context
  force_disable_category: true # true, if you really want to disable the relation with category
  contexts:
    default:  # the default context is mandatory
      providers:
        - sonata.media.provider.youtube
        - sonata.media.provider.image
        - sonata.media.provider.file

      formats:
        small: { width: 100 , quality: 70}
        big:   { width: 500 , quality: 70}

    cases:
      providers:
        - sonata.media.provider.image

    specialists:
      providers:
        - sonata.media.provider.image

    clients:
      providers:
        - sonata.media.provider.image
        - sonata.media.provider.file.svg

    videos:
      providers:
        - sonata.media.provider.image

    partners:
      providers:
        - sonata.media.provider.image
        - sonata.media.provider.file.svg

    medias:
      providers:
        - sonata.media.provider.image
        - sonata.media.provider.file
        - sonata.media.provider.file.svg

    static_pages:
      providers:
        - sonata.media.provider.image
        - sonata.media.provider.file

  cdn:
    server:
      path: /uploads/media # http://media.sonata-project.org/

  filesystem:
    local:
      directory:  "%kernel.root_dir%/../public/uploads/media" #flex
      create:     true

  providers:
    file:
      allowed_extensions: [ 'bmp', 'jpeg', 'png', 'jpg', 'svg', 'ico', 'gif', 'jpe', 'WebP', 'webp', 'xmp', 'ttf', 'sbv', 'psb', 'mpg', 'eps', 'avi', 'XLSX', 'mxf', 'Tif', 'PDF', 'DOCX', 'mp3', 'mov', 'm4v', 'm4a', 'mp4', '7zip', '7z', 'rar', 'zip', 'pdf', 'psd', 'gzip', 'ai', 'txt', 'tiff', 'tif', 'rtf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx', 'pttx', 'odt', 'odg', 'odp', 'ods', 'odc', 'odf', 'odb', 'csv', 'xml', 'tar', 'gz' ]
      allowed_mime_types: [ 'image/bmp', 'image/x-windows-bmp', 'image/gif', 'image/x-icon', 'image/jpeg', 'image/pjpeg', 'image/x-jps', 'image/jpg', 'image/png', 'image/svg+xml', 'image/webp', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'application/vnd.openxmlformats-officedocument.presentationml.presentation', 'image/vnd.adobe.photoshop', 'video/quicktime', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'video/mpeg', 'video/x-msvideo', 'image/x-eps', 'application/x-font-ttf', 'application/mxf', 'audio/mpeg', 'video/mp4', 'image/tiff', 'image/x-tiff', 'application/x-7z-compressed', 'application/mspowerpoint', 'application/msword', 'application/powerpoint', 'application/vnd.ms-powerpoint', 'application/x-mspowerpoint', 'application/postscript', 'multipart/x-gzip', 'application/pdf', 'application/x-pdf', 'application/rtf', 'text/html', 'text/rtf', 'text/plain', 'text/xml', 'application/x-gzip', 'application/x-compressed', 'application/x-zip-compressed', 'application/zip', 'application/x-tar',  'application/vnd.ms-excel', 'application/x-excel', 'application/x-msexcel', 'application/excel', 'application/octet-stream', 'application/xml', 'application/x-rar' ]
    image:
      allowed_extensions: ['jpg', 'png', 'jpeg', 'svg']
      allowed_mime_types: ['image/svg+xml', 'image/svg', 'image/pjpeg', 'image/jpeg', 'image/png', 'image/x-png']

  class:
    media: App\Application\Sonata\MediaBundle\Entity\Media
    gallery: App\Application\Sonata\MediaBundle\Entity\Gallery
    gallery_has_media: App\Application\Sonata\MediaBundle\Entity\GalleryHasMedia
