sonata_media:
  # if you don't use default namespace configuration
  #class:
  #    media: MyVendor\MediaBundle\Entity\Media
  #    gallery: MyVendor\MediaBundle\Entity\Gallery
  #    gallery_has_media: MyVendor\MediaBundle\Entity\GalleryHasMedia
  db_driver: doctrine_orm # or doctrine_mongodb, doctrine_phpcr it is mandatory to choose one here
  default_context: default # you need to set a context
  force_disable_category: true # true, if you really want to disable the relation with category
  contexts:
    default:  # the default context is mandatory
      providers:
        - sonata.media.provider.youtube
        - sonata.media.provider.image
        - sonata.media.provider.file

      formats:
        small: { width: 100 , quality: 70}
        big:   { width: 500 , quality: 70}

    cases:
      providers:
        - sonata.media.provider.image

    videos:
      providers:
        - sonata.media.provider.image

    partners:
      providers:
        - sonata.media.provider.image
        - sonata.media.provider.file.svg

    static_pages:
      providers:
        - sonata.media.provider.image
        - sonata.media.provider.file

  cdn:
    server:
      path: /uploads/media # http://media.sonata-project.org/

  filesystem:
    local:
      directory:  "%kernel.root_dir%/../public/uploads/media" #flex
      create:     true

  providers:
    image:
      allowed_extensions: ['jpg', 'png', 'jpeg', 'svg']
      allowed_mime_types: ['image/svg+xml', 'image/svg', 'image/pjpeg', 'image/jpeg', 'image/png', 'image/x-png']

  class:
    media: App\Application\Sonata\MediaBundle\Entity\Media
    gallery: App\Application\Sonata\MediaBundle\Entity\Gallery
    gallery_has_media: App\Application\Sonata\MediaBundle\Entity\GalleryHasMedia
