version: '3.7'

services:
  app:
    build:
      context: .docker/php/
    working_dir: /var/www/
    depends_on:
      - database
    volumes:
      - ./:/var/www/:rw,cached
      - ./.docker/php/fpm/php.ini:/usr/local/etc/php/php.ini
      - ./.docker/php/fpm/php-fpm.conf:/usr/local/etc/php/7.4/fpm/php-fpm.conf

  nginx:
    image: nginx:1.18
    depends_on:
      - app
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/:rw,cached
      - ./.docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./var/log/nginx/:/var/log/nginx:rw,delegated

  database:
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: agency