#%RAML 1.0 Library

types:
  Service:
    properties:
      id:
        description: Идентификатор
        type: integer
      title:
        description: Наименование услуги
        type: string
      slug:
        description: Уникальный слаг (ЧПУ)
        type: string
      sort:
        description: Индекс сортировки
        type: integer

  ListResponse:
    properties:
      services:
        type: Service[]
