published_schema:
  path: /system/schema
  controller: "raml.raml_bundle.controller.service_life_cycle:ramlAction"

published_schema_pretty:
  path: /schema/pretty
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: "raml/index.html.twig"