#%RAML 1.0 Library

types:
  Picture:
    properties:
      id:
        type: integer
      src:
        type: string
      filename:
        type: string
      description:
        type: string | nil
        required: false
      height:
        type: integer | nil
        required: false
      width:
        type: integer | nil
        required: false
      context:
        type: string | nil
        required: false
      copyright:
        type: string | nil
        required: false
      size:
        type: string

  Case:
    properties:
      id:
        description: Идентификатор
        type: integer
      title:
        description: Наименование кейса
        type: string
      slug:
        description: Уникальный слаг (ЧПУ)
        type: string
      excerpt:
        description: Краткое описание
        type: string
        required: false
      previewPicture:
        type: Picture | nil
        required: false

  ListResponse:
    properties:
      limit:
        description: Кол-во записей в списке
        type: number
        required: false
        minimum: 1
        maximum: 30
      offset:
        description: Отступ для записей
        type: number
        minimum: 0
        required: false
      cases:
        type: Case[]
