get:
  is: [hasErrors, hasCommonErrors, localable, pageable]
  description: "Список активных партнеров"
  responses:
    200:
      body:
        application/json:
          type: partnerTypes.ListResponse