#%RAML 1.0 Library

types:
  Partner:
    properties:
      id:
        description: Идентификатор
        type: integer
      name:
        description: Имя партнера
        type: string | nil
      sort:
        description: Индекс сортировки
        type: integer

  ListResponse:
    properties:
      partners:
        type: Partner[]
